pageInfo:
  title: Dashy
  description: Homelab
  navLinks:
    - title: Home
      path: /
  footerText: "Dashy"

appConfig:
  layout: auto
  iconSize: medium
  language: zh-TW


sections:
  - name: Media
    icon: fas fa-photo-video
    items:
      - title: Jellyfin
        description: Media Server
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/jellyfin.png
        url: https://jellyfin.haiyaa-sobel.cc/
        
      - title: Navidrome
        description: Music Server
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/navidrome.png
        url: https://music.haiyaa-sobel.cc
      
      - title: Immich
        description: Photo Backup
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png
        url: https://photo.haiyaa-sobel.cc
        
  - name: Downloads
    icon: fas fa-download
    items:
      - title: qBittorrent
        description: Torrent Client
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/qbittorrent.png
        url: https://qb.haiyaa-sobel.cc
        
  # - name: Sync
  #   icon: fas fa-sync-alt
  #   items:
  #     - title: Syncthing
  #       description: File Synchronization
  #       icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/syncthing.png
  #       url: http://192.168.0.196:8384
  
  - name: System / Infra
    icon: fas fa-server
    items:
      - title: Proxmox
        description: Virtualization Platform
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/proxmox.png
        url: http://192.168.0.114:8006

      - title: TrueNAS
        description: Storage / NAS System
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/truenas.png
        url: http://192.168.0.130

      - title: Portainer
        description: Docker 管理介面
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/portainer.png
        url: https://192.168.0.196:9443

      - title: AdGuard Home
        description: DNS 廣告過濾 / 網路保護
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/adguard-home.png
        url: http://192.168.0.196:8964
        
      - title: vnstat
        description: 流量統計
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/vn-stat.svg
        url: http://192.168.0.196:8685

      - title: Home Assistant
        description: 智慧家庭自動化中心
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/home-assistant.png
        url: http://homeassistant.local:8123

      # - title: Uptime Kuma
      #   description: Service Monitoring
      #   icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/uptime-kuma.png
      #   url: http://192.168.0.118:3001
      
      # - title: Dashy
      #   description: Dashboard
      #   icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/dashy.png
      #   url: http://192.168.0.196
  
  - name: Tools
    icon: fas fa-tools
    items:
      - title: Stirling PDF
        description: PDF Tools Suite
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/stirling-pdf.png
        url: https://pdf.haiyaa-sobel.cc
